#!/usr/bin/env ruby

require 'net/http'
require 'json'
require 'rubygems'
require 'rubygems/package'
require 'zlib'
require 'fileutils'

class Plugin


  # un-gzips the given IO, returning the
  # decompressed version as a StringIO
  def self.ungzip(tarfile)
    z = Zlib::GzipReader.new(tarfile)
    unzipped = StringIO.new(z.read)
    z.close
    unzipped
  end

  # untars the given IO into the specified
  # directory
  def self.untar(io, destination)
    Gem::Package::TarReader.new io do |tar|
      tar.each do |tarfile|
        destination_file = File.join destination, tarfile.full_name

        if tarfile.directory?
          FileUtils.mkdir_p destination_file
        else
          destination_directory = File.dirname(destination_file)
          FileUtils.mkdir_p destination_directory unless File.directory?(destination_directory)
          File.open destination_file, "wb" do |f|
            f.print tarfile.read
          end
        end
      end
    end
  end

  def self.host
    'plugins-server-1.cfapps.io'
  end

  def self.port
    80
  end

  def self.hostname
    "#{host}:#{port}"
  end

  def self.search(term = nil)
    uri = URI("http://#{hostname}/search#{term ? "?term=#{term}" : ""}")
    req = Net::HTTP::Get.new(uri)
    res = Net::HTTP.start(uri.hostname, uri.port) do |http|
      http.request(req)
    end

    plugins = JSON.parse(res.body)
    max_name_length = plugins.map { |p| p["name"].length }.max
    plugins.each do |plugin|
      printf "%-#{max_name_length}s : %s\n", "#{plugin["name"]}", plugin["description"]
    end
  end

  def self.install(name)
    Net::HTTP.start(host, port) do |http|
      resp = http.get("/download/#{name}")
      if 404 == resp.code.to_i
        puts "#{name} not found"
      else
        begin
          Dir.mkdir(File.expand_path("~/.cf-plugins"))
        rescue Errno::EEXIST
        end

        destination = File.expand_path("~/.cf-plugins/")
        body_io = StringIO.new(resp.body)
        untar(ungzip(body_io), destination)
        File.chmod(0755, File.expand_path("~/.cf-plugins/cf-#{name}"))

        puts "successfully installed #{name}"
      end
    end
  end

  def self.list
    Dir.glob(File.expand_path("~/.cf-plugins/cf-*")).each do |plugin|
      puts "* #{plugin[(File.expand_path("~/.cf-plugins/cf-").length)..-1]}"
    end
  end
end

cmd = ARGV[0] || "list"

def usage
  puts "cf plugins search # all available"
  puts "cf plugins search term # /.*term.*/i available"
  puts "cf plugins [list] # plugins currently installed"
  puts "cf plugins install [plugin]"
end

case cmd
when "search", "s"
  Plugin.search(ARGV.length > 1 && ARGV[1])
when "install", "i"
  Plugin.install(ARGV[1])
when "list", "l"
  Plugin.list
when "help", "--help", "-h"
  usage
end
